title: "Jannatul Ferdous Juicy"
description: "I am a results-driven and adaptable professional with a versatile skill set that enables me to excel across diverse fields. My unwavering commitment to continuous learning and innovation propels me toward achieving exceptional outcomes."
logo: Juicy-circle.png
show_downloads: false
theme: jekyll-theme-minimal
